- flatfs.go
filepath.Walk() sorts the names and calls lstat() on each entry, both of which are unnecessary when all we need are the key names in random order.
Instead I just use the fact that the directory layout is fixed and just use Readdirnames.
With a sample datastore with 100000 small keys the speedup is around 2.2:
```
100000 ORIG 3443.543417 (+/- 63.378649) ms
100000 OPT 1558.430242 (+/- 28.740522) ms
```
When there are only 10000 keys the speedup is around 1.3:
```
10000 ORIG 199.053565 (+/- 12.956540) ms
10000 OPT 151.882705 (+/- 8.869852) ms
```
> Improve Query Perforamance

- flatfs.go
- flatfs_test.go
Ignore non-directories in the top level directory to allow placing a README or similar file there.
This is based on #6.
> Ignore non-directories in the top level directory.

- flatfs.go
- flatfs_test.go
- readme.go
- shard.go
- util.go
Store the sharding function used in the file "SHARDING" in the repo.
To make this work the sharding function is now always specified as a
string.
> Store sharding function used in the repo.

- flatfs.go
0777 leaves the directory writable for all local users.
License: MIT
Signed-off-by: kpcyrd git@rxv.cc
> Fix permissions

- .travis.yml
- Makefile
- flatfs.go
- flatfs_test.go
This adds DiskUsage().
This datastore would have a big performance hit if we walked the
filesystem to calculate disk usage everytime.
Therefore I have opted to keep tabs of current disk usage by
walking the filesystem once during "Open" and then adding/subtracting
file sizes on Put/Delete operations.
On the plus:
* Small perf impact
* Always up to date values
* No chance that race conditions will leave DiskUsage with wrong values
On the minus:
* Slower Open() - it run Stat() on all files in the datastore
* Size does not match real size if a directory grows large
(at least on ext4 systems). We don't track directory-size changes,
only use the creation size.
> Feat: Implement a PersistentDatastore by adding DiskUsage method

- convert.go
- flatfs.go
- package.json
Since Go 1.5, os.Rename on Windows is consistent with other platforms. `go-os-rename` just enforced consistent behaviour on Windows before the change was made upstream, for other platforms it used the standard. Since both are the same now it seems redundant to keep it.
> Change go-os-rename to standard

- flatfs.go
Ran into this while updating our gx deps:
https://circleci.com/gh/qri-io/cafs/43
Not being able to write the temp file in the first place is the source of the failure, but handling errors before invoking defer statements on nil pointers is a good idea IMHO 😉
> check error before defer-removing disk usage file

- flatfs.go
We _expect_ temporary put- files.
> fix: only log when we find a file we don't expect

- flatfs.go
- flatfs_test.go
Otherwise, if we repeatedly stop the same node, we'll collect a bunch of temporary files and NEVER DELETE them. This will:
1. Waste space.
2. Slow down queries/GC.
This patch:
1. Moves all temporary files to a single `.temp` directory. The leading `.` means it can't conflict with any keys and queries (even on older flatfs versions) will skip it.
2. Adds an "rm -rf flatfs-dir/.temp" call on start.
> feat: put all temporary files in the same directory and clean them up

- .circleci/config.yml
- convert_test.go
- flatfs.go
- go.mod
- go.sum
- util_unix.go
- util_windows.go
* Windows opens files with the `FILE_SHARE_DELETE` mode to change behavior on rename.
* CI added to run tests on a windows executor
> Windows CI + Fixes

- flatfs.go
pull in from the higher level ds-datastore retry wrapper, so that retries can happen appropriately within the putMany operation.
> add fd-overload retries inline

- flatfs.go
- flatfs_test.go
When multiple write operations conflict, we:
1. Try them in-order till one succeeds.
2. After the fact, re-order them such that the pending operations "happen" after the one that succeeds.
3. Return "success" for all the pending write operations for that key. This is acceptable because we're claiming that the operation that _actually_ succeeded happened "last" so it would have clobbered the other operations.
However, in the case of put, we still need to remove the temporary file that we didn't end up moving into place.
> fix: remove temporary files when multiple write operations conflict

- flatfs.go
- go.mod
- util.go
- util_unix.go
- util_windows.go
Instead of retrying in get only, retry everywhere we read a file.
> feat: read harder

- flatfs.go
* Use a map for dirsToSync to avoid syncing the same dir multiple times.
* Keep track of files in a slice, and use offsets into the slice to keep track
of which ones have been closed/removed.
Also, record the fact that we've created a temporary file _before_ we try to write to it, in case the write fails. That way, we'll try to remove it when we abort.
> cleanup putMany implementation

- convert.go
- flatfs.go
- rename.go
- rename_plan9.go
os.Rename documentation says: "OS-specific restrictions may apply when
oldpath and newpath are in different directories." On Unix, this means
we can't rename across devices. On Plan 9 however, the functionality is
even more limited: cross-directory renames are not allowed at all.
Add a wrapper around os.Rename for Plan 9, which will copy the file if
we're renaming across directory. All tests seems to pass.
(Aside: I also had to write this wrapper to get go-git working on Plan 9:
https://github.com/go-git/go-billy/blob/v5.0.0/osfs/os_plan9.go#L27
but I notice few issues with that one.)
Fixes #86
> Add os.Rename wrapper for Plan 9

- readme.go
replace _charters_ by _characters_, which seems to be what was meant here, from a quick peek at my `~/.ipfs/blocks/`.
> fix typo in readme.go

- flatfs.go
I'm not entirely sure this should be supported but at the moment you could expect to terminate a query:
- call `Close()` on the  `Result`
- cancel the context
The second one though doesn't work as cancelling the context doesn't kill the query. This PR address that problem.
> query: also teard down on ctx done

- flatfs_test.go
In normal condition, this makes no difference as the complete test is pretty fast (~200ms), but
as soon as sync is enabled, this commit cut down the duration from 14s to 7s, on a fast SSD.
When running on a slower file system, this make a significant difference.
> test: faster TestNoCluster by batching the 3200 Puts

- flatfs.go
When doing a Put, the containing directory is always created. If it already exist,
no error bubbles up from `makeDirNoSync` and later this directly is always synced on disk
in `makeDir`.
This generate FS operations which are almost always unnecessary as the supporting folders
are quickly all created.
> perf: avoid syncing directories when they already existed

- flatfs.go
- shard.go
While I was trying to understand that code, I added some comment and documentation to make that process easier for the next person.
I also found a possible bug (https://github.com/ipfs/go-ds-flatfs/commit/26abf67dbdb624fa313b7fcd7d26a17ee3c18b89). It looks like a mistake as `fs` here can't be nil.
Additionally, I'm confused about certain things or noticed some possible improvement (https://github.com/ipfs/go-ds-flatfs/commit/846fdf9a6fa8caf7784649a458d6f8d72cb87c20). I'm using that PR as a way to discuss those points, this last commit can be removed after that.
> Comments, documentations and questions

- util_windows.go
This code was broken, it computed the size hint to do nothing with it.
Found with this profile:
This profile clearly show a pattern of `append`'s growth.
With this new code the only way to `append` is if the size hint undershoot (which would require more data to be written between the `Size` and `Read` calls). Might be worth a `panic("race")` or returning an error if that happen ?
> fix: actually use the size hint in util_windows.go

- flatfs.go
A global rand.Source was being used concurrently, which is not safe.
As stated [here](https://pkg.go.dev/math/rand@go1.24.0#NewSource):
> this source is not safe for concurrent use by multiple goroutines.
> Fix race condition due to concurrent use of rand source
